config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    # Dashboard
    namespace :google_shopping do
      get 'dashboard', to: 'dashboard#index', as: :dashboard
      resources :issues, only: [:index]
      post 'sync', to: 'dashboard#sync', as: :sync
      
      # Dedicated Product Manager
      resources :products, only: [:index, :edit, :update] do
        member do
          post :sync_one
          get :issues
        end
      end

      # Taxonomy Search
      resources :taxons, only: [] do
        collection do
          get :drill_down
        end
      end
    end

    # Settings Routes
    resource :google_merchant_settings, only: [:edit, :update] do
      get :connect
      get :callback
      delete :disconnect
      post :sync_now
    end
  end
end

app/controllers/spree/admin/google_shopping/dashboard_controller.rb
module Spree
  module Admin
    module GoogleShopping
      class DashboardController < Spree::Admin::BaseController
        helper Spree::Admin::BaseHelper
        
        before_action :check_connection, only: [:index]

        def index
          @store = Spree::Store.default
          @credential = @store.google_credential

          if @credential&.active? && @credential.merchant_center_id.present?
            service = Spree::GoogleShopping::StatusService.new(@credential)
            @stats = service.fetch_counts
            @last_sync = @credential.last_sync_at
            
            if @stats[:error]
              flash.now[:error] = "Could not fetch live stats from Google. Showing cached or empty data."
            end
          else

            @stats = { approved: 0, limited: 0, pending: 0, disapproved: 0 }
            @last_sync = nil
          end
        end

        def sync
          products = Spree::Product.all
          @store = Spree::Store.default
          
          if products.empty?
            flash[:error] = "No products found to sync."
          elsif @store.google_credential.merchant_center_id.blank?
            flash[:error] = "Please enter your Google Merchant Center ID in Settings before syncing."
          else
            products.each do |product|
              Spree::GoogleShopping::SyncProductJob.perform_later(product.id)
            end
            
            if @store.google_credential&.merchant_center_id
              Rails.cache.delete("google_shopping_stats_#{@store.google_credential.merchant_center_id}")
            end
            
            flash[:success] = "Sync started for #{products.count} products! Statuses will update shortly."
          end

          redirect_to admin_google_shopping_dashboard_path
        end

        private

        def check_connection
          credential = Spree::Store.default.google_credential
          
          unless credential&.active?
            flash[:warning] = "Please connect your Google Merchant Center account to access the dashboard."
            redirect_to edit_admin_google_merchant_settings_path
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/google_shopping/issues_controller.rb
module Spree
  module Admin
    module GoogleShopping
      class IssuesController < Spree::Admin::BaseController
        
        def index
          @total_variants = Spree::Variant.count
          @issues_summary = []

          attributes_with_issues = Spree::GoogleVariantAttribute
                                     .where.not(google_issues: nil)
                                     .where.not(google_issues: "[]")
          grouped_issues = {}

          attributes_with_issues.each do |attr|
            next if attr.google_issues.blank?

            attr.google_issues.each do |issue|
              key = issue['description']
              if grouped_issues[key].nil?
                variant = Spree::Variant.find_by(id: attr.variant_id)
                product_id = variant&.product_id
                grouped_issues[key] = {
                  short_title: issue['description'],
                  long_title: issue['detail'], 
                  code: issue['code'],
                  affected_count: 0,
                  severity: issue['servability'],
                  example_product_id: product_id
                }
              end
              
              grouped_issues[key][:affected_count] += 1
            end
          end

          @issues_summary = grouped_issues.values.sort_by { |i| -i[:affected_count] }
        end
      end
    end
  end
end

app/controllers/spree/admin/google_shopping/products_controller.rb
module Spree
  module Admin
    module GoogleShopping
      class ProductsController < Spree::Admin::ResourceController

        def model_class
          Spree::Product
        end

        def index
          per_page = params[:per_page].to_i > 0 ? params[:per_page].to_i : 25

          @search = Spree::Product.accessible_by(current_ability, :read).ransack(params[:q])
          
          @collection = @search.result(distinct: true)
                                      .includes(:google_product_attribute)
                                      .page(params[:page])
                                      .per(per_page)
        end

        def edit
          @product = Spree::Product.friendly.find(params[:id])
          @product.build_google_product_attribute unless @product.google_product_attribute
        end

        def update
          @product = Spree::Product.friendly.find(params[:id])
          if @product.update(product_params)

            Spree::GoogleShopping::SyncProductJob.perform_later(@product.id)
            
            flash[:success] = "Product updated. Syncing to Google Merchant Center"
            redirect_to admin_google_shopping_product_path(@product)
          else
            flash[:error] = "Could not update product"
            render :edit
          end
        end

        def issues
          @product = Spree::Product.friendly.find(params[:id])
          
          @variant = Spree::Variant.find_by(id: params[:variant_id])
          
          if @variant

            @google_attr = Spree::GoogleVariantAttribute.find_by(variant_id: @variant.id)
            @issues = @google_attr&.google_issues || []
          else
            flash[:error] = "Variant not found."
            redirect_to admin_google_shopping_product_path(@product)
          end
        end

        private

        def product_params
          params.require(:product).permit(
            google_product_attribute_attributes: [
              :id, 
              :brand, 
              :product_type,
              :google_product_category, 
              :gender, 
              :age_group, 
              :condition, 
              :gtin, 
              :mpn,
              :sale_start_at,
              :sale_end_at,
              :min_handling_time,
              :max_handling_time
            ]
          )
        end
      end
    end
  end
end

app/controllers/spree/admin/google_shopping/taxons_controller.rb
module Spree
    module Admin
      module GoogleShopping
        class TaxonsController < Spree::Admin::BaseController

          def drill_down
            parent_path = params[:parent_path]

            if parent_path.blank?

              categories = Spree::GoogleTaxon.pluck(:name).map { |n| n.split(' > ').first }.uniq.sort
            else

              prefix = "#{parent_path} > "
              
              categories = Spree::GoogleTaxon
                             .where("name LIKE ?", "#{prefix}%")
                             .pluck(:name)
                             .map { |n| n.sub(prefix, '').split(' > ').first }
                             .uniq
                             .sort
            end
  
            current_taxon_id = nil
            if parent_path.present?
              taxon = Spree::GoogleTaxon.find_by(name: parent_path)
              current_taxon_id = taxon&.google_id
            end
  
            render json: {
              categories: categories,
              current_id: current_taxon_id,
              is_leaf: categories.empty?
            }
          end
        end
      end
    end
  end

app/helpers/spree/admin/google_shopping_helper.rb
module Spree
    module Admin
      module GoogleShoppingHelper
  
        def google_supported_countries_options
          [
            ['United States (US)', 'US'], ['India (IN)', 'IN'], ['United Kingdom (GB)', 'GB'],
            ['Canada (CA)', 'CA'], ['Australia (AU)', 'AU'], ['Germany (DE)', 'DE'],
            ['France (FR)', 'FR'], ['Italy (IT)', 'IT'], ['Spain (ES)', 'ES'],
            ['Netherlands (NL)', 'NL'], ['Brazil (BR)', 'BR'], ['Japan (JP)', 'JP'],
            ['Mexico (MX)', 'MX'], ['Austria (AT)', 'AT'], ['Belgium (BE)', 'BE'],
            ['Denmark (DK)', 'DK'], ['Finland (FI)', 'FI'], ['Greece (GR)', 'GR'],
            ['Hungary (HU)', 'HU'], ['Indonesia (ID)', 'ID'], ['Ireland (IE)', 'IE'],
            ['Israel (IL)', 'IL'], ['Malaysia (MY)', 'MY'], ['New Zealand (NZ)', 'NZ'],
            ['Norway (NO)', 'NO'], ['Philippines (PH)', 'PH'], ['Poland (PL)', 'PL'],
            ['Portugal (PT)', 'PT'], ['Romania (RO)', 'RO'], ['Russia (RU)', 'RU'],
            ['Saudi Arabia (SA)', 'SA'], ['Singapore (SG)', 'SG'], ['South Africa (ZA)', 'ZA'],
            ['South Korea (KR)', 'KR'], ['Sweden (SE)', 'SE'], ['Switzerland (CH)', 'CH'],
            ['Taiwan (TW)', 'TW'], ['Thailand (TH)', 'TH'], ['Turkey (TR)', 'TR'],
            ['Ukraine (UA)', 'UA'], ['United Arab Emirates (AE)', 'AE'], ['Vietnam (VN)', 'VN']
            # Add others if needed based on GMC docs
          ].sort
        end
  
        def google_supported_currencies_options
          [
            ['US Dollar (USD)', 'USD'], ['Indian Rupee (INR)', 'INR'], ['British Pound (GBP)', 'GBP'],
            ['Euro (EUR)', 'EUR'], ['Canadian Dollar (CAD)', 'CAD'], ['Australian Dollar (AUD)', 'AUD'],
            ['Japanese Yen (JPY)', 'JPY'], ['Brazilian Real (BRL)', 'BRL'], ['Mexican Peso (MXN)', 'MXN'],
            ['Swiss Franc (CHF)', 'CHF'], ['Hong Kong Dollar (HKD)', 'HKD'], ['New Zealand Dollar (NZD)', 'NZD'],
            ['Polish Zloty (PLN)', 'PLN'], ['Russian Ruble (RUB)', 'RUB'], ['Singapore Dollar (SGD)', 'SGD'],
            ['South African Rand (ZAR)', 'ZAR'], ['South Korean Won (KRW)', 'KRW'], ['Swedish Krona (SEK)', 'SEK'],
            ['Turkish Lira (TRY)', 'TRY'], ['Danish Krone (DKK)', 'DKK'], ['Norwegian Krone (NOK)', 'NOK']
          ].sort
        end
  
      end
    end
  end

app/views/spree/admin/google_shopping/products/_filters.html.erb
<%# Spree 5 Filters Layout %>
<div class="filter-wrap py-3">
  <%= search_form_for [:admin, @search], url: admin_google_shopping_products_path do |f| %>
    <div class="d-flex flex-wrap gap-2">
      <div class="flex-grow-1">
        <div class="input-group">
          <%= f.text_field :name_cont, class: "form-control", placeholder: Spree.t(:search) %>
          <div class="input-group-append">
            <button type="submit" class="btn btn-primary">
              <%= icon('search') %>
            </button>
          </div>
        </div>
      </div>
      <%# You can re-enable the drawer logic if you want complex filters later %>
      <%# For now, a simple text search fits 90% of use cases %>
    </div>
  <% end %>
</div>

app/views/spree/admin/google_shopping/products/index.html.erb
<% content_for :page_title do %>
  <div style="display:flex; align-items:center; gap:10px;">
    <%= image_tag 'app_icons/google_merchant_logo.svg', width: 35, height: 35, alt: 'Google Merchant Logo' %>
    <span><%= Spree.t(:google_merchant_products) %></span>
  </div>
<% end %>

<% content_for :page_actions do %>
  <%= button_to admin_google_shopping_sync_path, method: :post, class: 'btn btn-primary' do %>
    <%= icon('refresh', class: 'mr-1') %> Sync All Products
  <% end %>
<% end %>

<div class="card mb-3">
  <div class="card-body p-3">
    <%= search_form_for [:admin, @search], url: admin_google_shopping_products_path do |f| %>
      <div class="row">
        <div class="col-12 col-md-6">
          <div class="input-group">
            <%= f.text_field :name_cont, class: "form-control", placeholder: "Search by name or SKU..." %>
            <div class="input-group-append">
              <button class="btn btn-primary" type="submit">
                <%= icon('search') %> Search
              </button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if @collection.any? %>
  <div class="table-responsive border rounded bg-white mb-3">
    <table class="table" id="listing_google_products">
      <thead>
        <tr>
          <th class="pl-4" colspan="2"><%= sort_link @search, :name, Spree.t(:name), {}, {title: 'admin_products_listing_name_title'} %></th>
          <th>Google Status</th>
          <th>Attributes (GTIN/Brand)</th>
          <th class="text-right pr-4"><%= Spree.t(:action) %></th>
        </tr>
      </thead>
      <tbody>
        <% @collection.each do |product| %>
          <%# Define the variable here so it can be used below %>
          <% g_attr = product.google_product_attribute %>
          
          <tr id="<%= dom_id product %>">

            <td class="pl-4" style="width: 60px;">
              <% if product.master.images.any? %>
                <%= link_to edit_admin_google_shopping_product_path(product) do %>
                  <%= image_tag main_app.url_for(product.master.images.first.url(:mini)), class: "rounded border", style: "width: 48px; height: 48px; object-fit: cover;" %>
                <% end %>
              <% else %>
                <div class="rounded border bg-light d-flex align-items-center justify-content-center text-muted" style="width: 48px; height: 48px;">
                  <%= icon('image', width: 20, height: 20) %>
                </div>
              <% end %>
            </td>
            <td>
              <%= link_to product.name, edit_admin_google_shopping_product_path(product), class: "text-dark font-weight-bold d-block mb-1" %>
              <% if product.sku.present? %>
                <span class="badge badge-active border" style="background-color: #e8f5e9; color: #2e7d32;">
                  <%= icon('check', class: 'mr-1') %> <%= product.sku %>
                </span>
              <% else %>
                <span class="badge badge-danger">
                  <%= icon('alert-circle', class: 'mr-1') %> No SKU
                </span>
              <% end %>
            </td>
            <td>
              <% case g_attr&.google_status %>
              <% when 'approved' %>
                <span class="badge badge-success">
                  <%= icon('check', class: 'mr-1') %> Approved
                </span>
              
              <% when 'pending' %>
                <span class="badge badge-warning text-white">
                  <%= icon('clock', class: 'mr-1') %> Pending
                </span>

              <% when 'disapproved' %>
                <span class="badge badge-danger">
                  <%= icon('alert-triangle', class: 'mr-1') %> Disapproved
                </span>
              <% else %>
                <span class="badge badge-light border">
                  <%= icon('circle', class: 'mr-1 text-muted') %> Not Synced
                </span>
              <% end %>
            </td>
            <td>
              <div class="d-flex align-items-center gap-2">
                <% if g_attr&.gtin.present? %>
                  <span class="text-success small" title="GTIN Present"><%= icon('check') %> GTIN</span>
                <% else %>
                  <span class="text-danger small" title="Missing GTIN"><%= icon('x') %> GTIN</span>
                <% end %>
                <span class="text-muted">|</span>
                <% if g_attr&.brand.present? %>
                  <span class="text-success small" title="Brand Present"><%= icon('check') %> Brand</span>
                <% else %>
                  <span class="text-danger small" title="Missing Brand"><%= icon('x') %> Brand</span>
                <% end %>
              </div>
            </td>
            <td class="actions text-right pr-4">
              <div class="d-flex justify-content-end align-items-center gap-1">
                <%= button_to sync_one_admin_google_shopping_product_path(product), method: :post, class: "btn btn-outline-primary btn-sm mr-1", title: "Push to Google" do %>
                  <%= icon('refresh', width: 16, height: 16) %>
                <% end %>
                <%= link_to_edit product, url: edit_admin_google_shopping_product_path(product), no_text: true, class: 'btn btn-light btn-sm' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= render 'spree/admin/shared/index_table_options', collection: @collection %>

<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: "Products") %>
  </div>
<% end %>

app/views/spree/admin/google_shopping/products/issues.html.erb
<% content_for :page_title do %>
    Google Shopping Issues
  <% end %>
  
  <% content_for :page_actions do %>
    <%= button_link_to "Back to Product", edit_admin_google_shopping_product_path(@product), icon: 'arrow-left', class: 'btn-light' %>
  <% end %>
  
  <div class="card">
    <div class="card-header">
      <h5 class="mb-0">
        Issues for Variant: <strong><%= @variant.sku %></strong> 
        <small class="text-muted">(<%= @variant.options_text %>)</small>
      </h5>
    </div>
  
    <div class="table-responsive">
      <table class="table">
        <thead class="thead">
          <tr>
            <th style="width: 20%">Error Code</th>
            <th style="width: 30%">Description</th>
            <th>Detail / Suggestion</th>
          </tr>
        </thead>
        <tbody>
          <% if @issues.any? %>
            <% @issues.each do |issue| %>
              <tr>
                <td>
                  <span class="badge badge-danger"><%= issue['code'] || 'API Error' %></span>
                </td>
                <td><strong><%= issue['description'] %></strong></td>
                <td class="text-muted"><%= issue['detail'] %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="3" class="text-center text-success py-4">
                <i class="icon icon-check fa-2x"></i><br>
                No issues detected for this variant.
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>