config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    # Dashboard
    namespace :google_shopping do
      get 'dashboard', to: 'dashboard#index', as: :dashboard
      resources :issues, only: [:index]
      post 'sync', to: 'dashboard#sync', as: :sync
      
      # Dedicated Product Manager
      resources :products, only: [:index, :edit, :update] do
        member do
          post :sync_one
          get :issues
        end
      end

      # Taxonomy Search
      resources :taxons, only: [] do
        collection do
          get :drill_down
        end
      end
    end

    # Settings Routes
    resource :google_merchant_settings, only: [:edit, :update] do
      get :connect
      get :callback
      delete :disconnect
      post :sync_now
    end
  end
end

app/controllers/spree/admin/google_shopping/products_controller.rb
module Spree
  module Admin
    module GoogleShopping
      class ProductsController < Spree::Admin::ResourceController

        def model_class
          Spree::Product
        end

        def index
          per_page = params[:per_page].to_i > 0 ? params[:per_page].to_i : 25

          @search = Spree::Product.accessible_by(current_ability, :read).ransack(params[:q])
          
          @collection = @search.result(distinct: true)
                                      .includes(:google_product_attribute)
                                      .page(params[:page])
                                      .per(per_page)
        end

        def edit
          @product = Spree::Product.friendly.find(params[:id])
          @product.build_google_product_attribute unless @product.google_product_attribute
        end

        def update
          @product = Spree::Product.friendly.find(params[:id])
          if @product.update(product_params)

            Spree::GoogleShopping::SyncProductJob.perform_later(@product.id)
            
            flash[:success] = "Product updated. Syncing to Google Merchant Center"
            redirect_to admin_google_shopping_product_path(@product)
          else
            flash[:error] = "Could not update product"
            render :edit
          end
        end

        def issues
          @product = Spree::Product.friendly.find(params[:id])
          
          @variant = Spree::Variant.find_by(id: params[:variant_id])
          
          if @variant

            @google_attr = Spree::GoogleVariantAttribute.find_by(variant_id: @variant.id)
            @issues = @google_attr&.google_issues || []
          else
            flash[:error] = "Variant not found."
            redirect_to admin_google_shopping_product_path(@product)
          end
        end

        private

        def product_params
          params.require(:product).permit(
            google_product_attribute_attributes: [
              :id, 
              :brand, 
              :product_type,
              :google_product_category, 
              :gender, 
              :age_group, 
              :condition, 
              :gtin, 
              :mpn,
              :sale_start_at,
              :sale_end_at,
              :min_handling_time,
              :max_handling_time
            ]
          )
        end
      end
    end
  end
end

app/views/spree/admin/products/google_shopping.html.erb
<%= render 'spree/admin/shared/product_tabs', current: :google_shopping %>

<% content_for :page_title do %>
  Google Shopping Attributes
<% end %>

<%= form_for [:admin, @product], url: admin_product_path(@product), method: :put do |f| %>
  <div class="card mb-3">
    <div class="card-header">
      <h5 class="card-title mb-0">Basic Information</h5>
    </div>
    <div class="card-body">
      <%= f.fields_for :google_product_attribute do |g| %>
        
        <div class="form-group">
          <%= g.label :brand, "Brand Name" %>
          <%= g.text_field :brand, class: 'form-control' %>
        </div>

        <div class="row">
          <div class="col-6">
            <div class="form-group">
              <%= g.label :gtin, "GTIN / UPC / EAN" %>
              <%= g.text_field :gtin, class: 'form-control' %>
              <small class="form-text text-muted">Leave empty if custom product.</small>
            </div>
          </div>
          <div class="col-6">
             <div class="form-group">
              <%= g.label :mpn, "MPN (Manufacturer Part Number)" %>
              <%= g.text_field :mpn, class: 'form-control' %>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col-4">
             <div class="form-group">
              <%= g.label :condition %>
              <%= g.select :condition, ['new', 'refurbished', 'used'], {}, class: 'select2' %>
            </div>
          </div>
          <div class="col-4">
             <div class="form-group">
              <%= g.label :gender %>
              <%= g.select :gender, ['', 'male', 'female', 'unisex'], {}, class: 'select2' %>
            </div>
          </div>
           <div class="col-4">
             <div class="form-group">
              <%= g.label :age_group %>
              <%= g.select :age_group, ['', 'adult', 'kids', 'toddler', 'infant'], {}, class: 'select2' %>
            </div>
          </div>
        end %>
      <% end %>
    </div>
  </div>
  
  <div class="form-actions" data-hook="buttons">
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </div>
<% end %>